### ISSUE TITLE
Update to work with Ubuntu 20.04

### ISSUE THREAD

**Issue by GabubuAvailable** [gammu/wammu#101]
Hello. I was wondering when are you gonna update it to work with Ubuntu 20.04? And it needs to verify in .py files. I tried installing it, running it but it doesn't work. It gave me an error.

Installing it:
```
gabubu@Ubuntu-110-15IBR:~/Downloads/wammu-0.44$ sudo python setup.py
[sudo] password for gabubu: 
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

Running it:
```
gabubu@Ubuntu-110-15IBR:~/Downloads/wammu-0.44$ sudo python wammu.py
Traceback (most recent call last):
  File "wammu.py", line 47, in <module>
    import Wammu.Locales
  File "/home/gabubu/Downloads/wammu-0.44/Wammu/Locales.py", line 31, in <module>
    import six
ImportError: No module named six
```

Please, if you still working on updates, please, fix it...

**Comment by nijel** [comment]
How about installing the dependencies first?

**Comment by GabubuAvailable** [comment]
I tried and it worked. Thanks. And sorry for this delay :D
