### ISSUE TITLE
Wammu does not start on Windows XP SP3 ( WindowsError: [Error -2146893795] )

### ISSUE THREAD

**Issue by Baltazar500** [gammu/wammu#85]
Wammu does not start on Windows XP SP3. On start i get error "See the logfile 'C:\Program Files\Wammu\wammu.exe.log' for details". In wammu.exe.log i see next :

Traceback (most recent call last):
  File "wammu.py", line 199, in <module>
  File "Wammu\App.pyo", line 29, in <module>
  File "Wammu\Main.pyo", line 34, in <module>
  File "tempfile.pyo", line 35, in <module>
  File "random.pyo", line 887, in <module>
  File "random.pyo", line 97, in __init__
  File "random.pyo", line 115, in seed
WindowsError: [Error -2146893795] 
Traceback (most recent call last):
  File "wammu.py", line 199, in <module>
  File "Wammu\App.pyo", line 29, in <module>
  File "Wammu\Main.pyo", line 34, in <module>
  File "tempfile.pyo", line 35, in <module>
  File "random.pyo", line 887, in <module>
  File "random.pyo", line 97, in __init__
  File "random.pyo", line 115, in seed
WindowsError: [Error -2146893795]

**Comment by Kabak85** [comment]
Hi,

I had the same error here. The DLL from microsoft in the wammu directory are not compatible with XP. You have to remove it.

**Comment by Baltazar500** [comment]
>Edit You have to remove :

Thanks for your reply. This solution worked for me. Wammu successfully launched on Windows XP SP3.
